[package]
name = "demangle"
version = "0.1.0"
authors = ["Jing Peng <pj.hades@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-demangle = "^0.1.18"
regex = "^1.4.6"
lazy_static = "^1.4.0"
